// Reads real README.md / CLAUDE.md files from each project's folder in the
// monorepo and bakes their content into src/data/projectDocs.generated.ts so
// the dashboard can render real documentation without a backend.
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const OUT_FILE = join(__dirname, '..', 'src', 'data', 'projectDocs.generated.ts');

// id -> { path, docFiles: [candidate filenames in priority order] }
const SOURCES = {
  'investing-game': { path: '01_investment_core/01_simulate/investing_game/02-Investing-Game', docs: ['README.md', 'CLAUDE.md'] },
  'full-finance-game': { path: '01_investment_core/01_simulate/full_finance_game', docs: ['README.md'] },
  'game-agents-simulation': { path: '01_investment_core/01_simulate/game_agents_simulation/agent-wealth', docs: ['README.md', 'CLAUDE.md'] },
  'agente-contenido': { path: '01_investment_core/03_publish/agente_contenido', docs: ['README.md', 'CLAUDE.md'] },
  'historias-automatizadas': { path: '01_investment_core/03_publish/historias_automatizadas', docs: ['README.md', 'CLAUDE.md'] },
  'conway-1v1': { path: '02_pm_tower/01_simulate/conway_game_of_life_1v1', docs: ['README.md', 'CLAUDE.md'] },
  'aoe2-agents': { path: '02_pm_tower/01_simulate/aoe2_agents_conway_variant', docs: ['README.md', 'CLAUDE.md'] },
  'pm-control-tower': { path: '02_pm_tower/02_analyze/agentic_pm_control_tower', docs: ['README.md', 'CLAUDE.md'] },
  'pm-maturity-engine': { path: '02_pm_tower/02_analyze/pm-maturity-engine', docs: ['README.md'] },
  'strategic-bn-pm-nes': { path: '02_pm_tower/02_analyze/strategic_bn_pm_nes', docs: ['README.md', 'Claude.md'] },
  'supplychain-game': { path: '03_supply_obs/01_simulate/supplychain_game', docs: ['README.md', 'CLAUDE.md'] },
  'supply-chain-observatory': { path: '03_supply_obs/02_analyze/supply_chain_maturity_observatory', docs: ['README.md', 'architecture.md'] },
  'excel-agent': { path: '03_supply_obs/02_analyze/excel_agent', docs: ['README.md', 'CLAUDE.md'] },
  'thesis-brain': { path: '04_nes_engine/02_analyze/thesis_brain', docs: ['README.md', 'CLAUDE.md'] },
};

const MAX_CHARS = 6000;

const docs = {};
for (const [id, { path, docs: candidates }] of Object.entries(SOURCES)) {
  let content = null;
  let sourceFile = null;
  for (const candidate of candidates) {
    const full = join(REPO_ROOT, path, candidate);
    if (existsSync(full)) {
      content = readFileSync(full, 'utf-8');
      sourceFile = candidate;
      break;
    }
  }
  if (content) {
    if (content.length > MAX_CHARS) {
      content = content.slice(0, MAX_CHARS) + '\n\n… _(truncado — ver archivo completo en el repositorio)_';
    }
    docs[id] = { sourceFile, content };
  }
}

const banner = '// AUTO-GENERATED by scripts/generate-docs.mjs — do not edit by hand.\n// Re-run `node scripts/generate-docs.mjs` after updating source READMEs.\n';
const body = `${banner}\nexport interface ProjectDoc {\n  sourceFile: string;\n  content: string;\n}\n\nexport const PROJECT_DOCS: Record<string, ProjectDoc> = ${JSON.stringify(docs, null, 2)};\n`;

writeFileSync(OUT_FILE, body, 'utf-8');
console.log(`Wrote ${Object.keys(docs).length} project docs to ${OUT_FILE}`);
